### PR TITLE
gfx: shell: add btn_favorite.tga and btn_unfavorite.tga

### PR DESCRIPTION
**Pull request by Vladislav4KZ**

### CODE REVIEW

**Comment by Vladislav4KZ** [comment]
I didn't underline the letters for these picbuttons, as there are no hotkeys for them.

**Comment by a1batross** [comment]
Didn't noticed that PR. I think underlining 'a' is fine there, as 'f' would be used by Filter button.

**Comment by Vladislav4KZ** [comment]
> Didn't noticed that PR. I think underlining 'a' is fine there, as 'f' would be used by Filter button.

@a1batross Ok, so I can still create these picbuttons, but with an underlined 'a'?

**Comment by Vladislav4KZ** [comment]
I closed the PR because I saw that you removed the use of these TGAs in the MainUI code.

**Comment by a1batross** [comment]
@Vladislav4KZ yeah. There is no way to make an underline through the text renderer, because it kinda supports underlining but only on Windows, and despite my best attempts at making them look like original btns_main.bmp, it's just nowhere near it.

I removed the use of TGAs that's because they were spamming the console. :D

**Pull request closed without merging**
