### PR TITLE
touch_default: convert touch buttons to PNG.

### PR DESCRIPTION
**Pull request by nekonomicon**

### CODE REVIEW

**Comment by a1batross** [comment]
Did you just converted them, or tried to optimize the filters with tools like pngcrush?

**Comment by nekonomicon** [comment]
Just converted without additional chunks.

**Comment by nekonomicon** [comment]
I tried to use optipng, but this application creates indexed image with `tRNS` chunk instead of grayscale+alpha.

**Comment by a1batross** [comment]
@nekonomicon good, I just wanted to make sure it's unmodified images, so we can experiment on that later.

**Pull request merged**
